---
title: "About this blog"
about:
  template: jolla
  links:
    - icon: globe
      text: My main website
      href: https://cknotz.github.io
    - icon: linkedin
      text: LinkedIn
      href: https://www.linkedin.com/in/cknotz
    - icon: github
      text: Github
      href: https://github.com/cknotz
    - icon: envelope
      text: Mail
      href: mailto:carlo.knotz@uis.no

---

**Hi!**

My name is Carlo and I teach political science, including data analysis, at the [University of Stavanger](https://www.uis.no/nb/profile/carlo-michael-knotz-0) in Norway.

I often find that students have quite smart ideas that they want to test in a course paper or thesis project and which *could* be tested with a relatively simple quantitative analysis -- but they don't quite know how to actually go about this (and might be intimidated by quantitative methods).

The aim of this blog is to show students (in the social sciences so far) how they can **test big ideas** -- e.g., about the role of class, social norms, or gender -- **with relatively simple methods** that they should be familiar with from their introductory statistics course and with the free and open-source `R` statistical programming language.

The posts are very much focussed on explaining the general logic of an analysis and assume that readers are at least a bit familiar with basic statistics and data analysis methods and how to do them in `R` (mainly; some posts also use other languages such as `Javascript`). Each post also gives pointers to more advanced resources (textbooks, journal articles) on quantitative methods.






