<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Carlo Knotz">
<meta name="dcterms.date" content="2025-03-10">

<title>How vulnerable are workers to globalization (and what effects does this have)? – Testing big ideas with simple methods</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-707d8167ce6003fca903bfe2be84ab7f.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-f93c2b1f3f0577f377aefa4848a86a36.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-5100b8561cd7f6cd8c35657ed6fe7ee7.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-f93c2b1f3f0577f377aefa4848a86a36.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script src="../../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Testing big ideas with simple methods</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About this blog</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">How vulnerable are workers to globalization (and what effects does this have)?</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">Survey data</div>
                <div class="quarto-category">Globalization</div>
                <div class="quarto-category">Merging data</div>
                <div class="quarto-category">ESS</div>
                <div class="quarto-category">Political science</div>
                <div class="quarto-category">Sociology</div>
                <div class="quarto-category">Economics</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Carlo Knotz </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">March 10, 2025</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#the-losers-of-globalization-and-trade" id="toc-the-losers-of-globalization-and-trade" class="nav-link active" data-scroll-target="#the-losers-of-globalization-and-trade">The losers of globalization and trade</a></li>
  <li><a href="#accessing-the-data" id="toc-accessing-the-data" class="nav-link" data-scroll-target="#accessing-the-data">Accessing the data</a></li>
  <li><a href="#importing-and-merging-the-data-with-ess-data" id="toc-importing-and-merging-the-data-with-ess-data" class="nav-link" data-scroll-target="#importing-and-merging-the-data-with-ess-data">Importing and merging the data with <em>ESS</em> data</a>
  <ul class="collapse">
  <li><a href="#preparation" id="toc-preparation" class="nav-link" data-scroll-target="#preparation">Preparation</a></li>
  <li><a href="#data-import" id="toc-data-import" class="nav-link" data-scroll-target="#data-import">Data import</a></li>
  <li><a href="#a-quick-exploration" id="toc-a-quick-exploration" class="nav-link" data-scroll-target="#a-quick-exploration">A quick exploration</a></li>
  <li><a href="#adjusting-the-isco-scores" id="toc-adjusting-the-isco-scores" class="nav-link" data-scroll-target="#adjusting-the-isco-scores">Adjusting the ISCO scores</a></li>
  <li><a href="#merging-the-datasets" id="toc-merging-the-datasets" class="nav-link" data-scroll-target="#merging-the-datasets">Merging the datasets</a></li>
  </ul></li>
  <li><a href="#vulnerability-to-globalization-gender-age-and-political-trust" id="toc-vulnerability-to-globalization-gender-age-and-political-trust" class="nav-link" data-scroll-target="#vulnerability-to-globalization-gender-age-and-political-trust">Vulnerability to globalization, gender, age, and political trust</a></li>
  <li><a href="#next-steps" id="toc-next-steps" class="nav-link" data-scroll-target="#next-steps">Next steps</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">






<section id="the-losers-of-globalization-and-trade" class="level2">
<h2 class="anchored" data-anchor-id="the-losers-of-globalization-and-trade">The losers of globalization and trade</h2>
<p>Free trade and globalization are back on the political agenda. Starting with the <em>Brexit</em> campaign in 2015 and the UK’s subsequent actual exit from the European Union and now, in 2025, with Donald Trump taking the US into a trade war with essentially the rest of the world, there is a new discussion about the benefits but also drawbacks of free trade <span class="citation" data-cites="Colantone2018 Colantone2018a Colantone2019 Agnolinetal2025">(see also <a href="#ref-Colantone2018" role="doc-biblioref">Colantone and Stanig 2018b</a>, <a href="#ref-Colantone2018a" role="doc-biblioref">2018a</a>, <a href="#ref-Colantone2019" role="doc-biblioref">2019</a>; <a href="#ref-Agnolinetal2025" role="doc-biblioref">Agnolin, Colantone, and Stanig 2025</a>)</span>.</p>
<p>And, indeed, even though free trade is generally beneficial for economic growth and development, there are usually some workers who are negatively affected by increased competition from abroad <span class="citation" data-cites="Autoretal2013 Heckscher1919 Ohlin1933">(<a href="#ref-Autoretal2013" role="doc-biblioref">Autor, Dorn, and Hanson 2013</a>; <a href="#ref-Heckscher1919" role="doc-biblioref">Heckscher 1919</a>; <a href="#ref-Ohlin1933" role="doc-biblioref">Ohlin 1933</a>)</span>. These negative economic effects can then also have further political and social effects, for example in the form of increased demands for social protection <span class="citation" data-cites="Walter2010">(<a href="#ref-Walter2010" role="doc-biblioref">Walter 2010</a>)</span>, increased political polarization and conflict <span class="citation" data-cites="Autoretal2020">(<a href="#ref-Autoretal2020" role="doc-biblioref">Autor et al. 2020</a>)</span>, or rising rates of child poverty, out-of-wedlock births, and premature deaths among men <span class="citation" data-cites="Autoretal2019">(<a href="#ref-Autoretal2019" role="doc-biblioref">Autor, Dorn, and Hanson 2019</a>)</span>.</p>
<p>To be able to study these (and potentially other) effects, researchers use measurements of how exposed and vulnerable workers are to the negative effects of trade and international competition. One way to measure this is with <strong>indicators of ‘offshoreability’</strong> — how easy or difficult is it to move the work done by people in different occupations to other countries? Different such indicators have been developed, but one that is relatively widely used are the indicators of offshoreability by Blinder &amp; Krueger <span class="citation" data-cites="Blinder2013">(<a href="#ref-Blinder2013" role="doc-biblioref">2013</a>)</span>. They use a survey-based approach, where they ask workers about their perceptions of how easy it would be to move their jobs abroad and confirm this with a second survey of experts.</p>
<p>The rest of this post will show you how you can access measures of worker’s vulnerability to trade and globalization, how you import them into <code>R</code>, and how you merge them with data from round 7 (2014) of the <em>European Social Survey</em> so that you can analyze how vulnerability to globalization affects people’s attitudes and behavior.</p>
</section>
<section id="accessing-the-data" class="level2">
<h2 class="anchored" data-anchor-id="accessing-the-data">Accessing the data</h2>
<p>The Blinder/Krueger measurements of vulnerability to trade (i.e., <em>“offshoreability”</em>) are publicly available as part of the <em>replication data package</em> of a second (important) research article, which compares the effects of globalization and technological change on workers <span class="citation" data-cites="Goosetal2014">(<a href="#ref-Goosetal2014" role="doc-biblioref">Goos, Manning, and Salomons 2014</a>)</span>. Goos et al.&nbsp;have archived the research data they use in the <em>ICPSR</em> Data Archive: <a href="https://doi.org/10.3886/E112846V1" target="_blank">https://doi.org/10.3886/E112846V1</a>. There, under <em>Data</em>, is the <code>task.dta</code> dataset, which contains the offshoreability scores and, as a bonus, also additional scores on how exposed workers are to losing their jobs to robots and other automated technology <span class="citation" data-cites="Autoretal2003 Thewissen2019">(from <a href="#ref-Autoretal2003" role="doc-biblioref">Autor, Levy, and Murnane 2003</a>; used by e.g., <a href="#ref-Thewissen2019" role="doc-biblioref">Thewissen and Rueda 2019</a>)</span>. You can download the dataset for free, after a quick login.</p>
</section>
<section id="importing-and-merging-the-data-with-ess-data" class="level2">
<h2 class="anchored" data-anchor-id="importing-and-merging-the-data-with-ess-data">Importing and merging the data with <em>ESS</em> data</h2>
<section id="preparation" class="level3">
<h3 class="anchored" data-anchor-id="preparation">Preparation</h3>
<p>Merging the data with <em>ESS</em> survey data is not as difficult as it might seem. The first step is to make sure that you also have access to <em>ESS</em> data (which can be downloaded for free from <a href="https://www.europeansocialsurvey.org/" target="_blank">europeansocialsurvey.org</a>), and that both datasets are stored in your current <em>working directly</em> (“folder”) so that <code>R</code> can directly find and import them. As mentioned above, the example here uses data from the 7th <em>ESS</em> round, so if you do not already have the data on your computer, quickly download them (in <code>Stata</code>/<code>.dta</code> format).</p>
<p>In <code>R</code>, we first load the <code>tidyverse</code> because it contains functions that we need to be able to work with and visualize the data. I am also setting the <code>ggplot</code> theme to <code>classic</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   4.0.0     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.4     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_classic</span>())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="data-import" class="level3">
<h3 class="anchored" data-anchor-id="data-import">Data import</h3>
<p>Then we first import the <em>ESS</em> dataset with <code>haven</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>ess7 <span class="ot">&lt;-</span> haven<span class="sc">::</span><span class="fu">read_dta</span>(<span class="st">"ess7.dta"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The <em>ESS</em> is quite big, so to make things easier we select only a few variables that we want to work with:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>ess7 <span class="sc">%&gt;%</span> </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(idno,cntry,essround,isco08,gndr,agea,trstplt) <span class="ot">-&gt;</span> ess7</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li><code>idno</code> and <code>essround</code> are “administrative” variables that are always good to keep</li>
<li><code>cntry</code> designates which country a given respondent comes from, and this one should always be kept</li>
<li><code>isco08</code> is the respondents’ occupation as measured by the 2008 version of the <em>International Standard Classification of Occupations</em> (<em>ISCO</em>; see also the other post on <a href="https://cknotz.github.io/getstuffdone_blog/posts/measuringclass/" target="_blank">measuring class</a>). This variable is important because we will use it to link the <em>ESS</em> data with the vulnerability indicator data</li>
<li><code>agea</code>, <code>gndr</code>, and <code>trstplt</code> measure the respondents’ age, gender, and their trust in politicans (on a 0-10 scale)</li>
</ul>
<p>Next, we import the vulnerability indicator scores:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>scores <span class="ot">&lt;-</span> haven<span class="sc">::</span><span class="fu">read_dta</span>(<span class="st">"task.dta"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="a-quick-exploration" class="level3">
<h3 class="anchored" data-anchor-id="a-quick-exploration">A quick exploration</h3>
<p>It is time to take a quick look at the data to get a sense of what we are working with:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(scores)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 7
  occupation           RTI_alm_isco_77     BK OFF1_ffl OFF2_ffl OFF3_ffl OFF_gms
  &lt;dbl+lbl&gt;                      &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;
1 12 [Corporate manag…          -0.747 -0.320   -1.43     0.798   -1.66   -0.593
2 13 [Managers of sma…          -1.52  -0.634   -0.937    0.265   -1.19   -0.593
3 21 [Physical, mathe…          -0.822  1.05     0.390    0.798   -1.48   -0.375
4 22 [Life science an…          -1.00  -0.758   -1.92     0.544   -1.70   -0.639
5 24 [Other professio…          -0.732  0.212   -0.892    1.56    -1.18   -0.513
6 31 [Physical, mathe…          -0.397 -0.123    0.116   -0.393   -0.433  -0.272</code></pre>
</div>
</div>
<p>You might notice that every row in the dataset is an <em>occupation</em>: Row #1 is “Corporate managers”, row #2 is “Managers of small enterprises”, and so on. The first column (or variable) indicates the title of the occupation and a 2-digit code based on the 1988 version of the <em>International Standard Classifiation of Occupations</em> (<em>ISCO</em>) classification, where “Corporate managers” have the code <code>12</code>.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> The other variables are different indicators of vulnerability:</p>
<ul>
<li><code>RTI_alm_isco_77</code> is an indicator of vulnerability to automation (“routine task intensity”) that was developed by Autor, Levy, and Murnane <span class="citation" data-cites="Autoretal2003">(<a href="#ref-Autoretal2003" role="doc-biblioref">2003</a>)</span>;</li>
<li><code>BK</code> is the indicator of offshoreability by Blinder &amp; Krueger <span class="citation" data-cites="Blinder2013">(<a href="#ref-Blinder2013" role="doc-biblioref">2013</a>)</span>;</li>
<li><code>OFF1_ffl</code> to <code>OFF3_ffl</code> are alternative indicators of offshoreability by Firpo et al. <span class="citation" data-cites="Firpoetal2011">(see their paper for details: <a href="#ref-Firpoetal2011" role="doc-biblioref">Firpo, Fortin, and Lemieux 2011</a>)</span>;</li>
<li><code>OFF_gms</code> is the <code>BK</code> indicator in a normalized (“rescaled”) version;</li>
</ul>
<p>Let’s take a closer look at the <code>BK</code> indicator:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(scores<span class="sc">$</span>BK)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
-0.9985 -0.7585 -0.3203  0.0000  0.3996  2.3458 </code></pre>
</div>
</div>
<p>The indicator ranges from (almost) -1 to 2.35 and is centered on 0. Maybe more interesting is to see which occupations are particularly exposed to globalization. To see that, we reorder the data from the highest to lowest <code>BK</code> score and let <code>R</code> display the five highest-scoring occupations:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>scores <span class="sc">%&gt;%</span> </span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="sc">-</span>BK) <span class="sc">%&gt;%</span> </span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 7
  occupation            RTI_alm_isco_77    BK OFF1_ffl OFF2_ffl OFF3_ffl OFF_gms
  &lt;dbl+lbl&gt;                       &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;
1 82 [Machine operator…           0.493 2.35     1.66    -1.02   0.993     3.18 
2 73 [Precision, handi…           1.59  1.66     0.585   -0.564  0.00830  -0.616
3 81 [Stationary plant…           0.323 1.59     0.990   -1.41   0.306     1.63 
4 74 [Other craft and …           1.24  1.15     1.49    -0.453  1.07     -0.272
5 21 [Physical, mathem…          -0.822 1.05     0.390    0.798 -1.48     -0.375
6 41 [Office clerks]              2.24  0.400    0.301    1.26   0.913     1.21 </code></pre>
</div>
</div>
<p>Evidently, typical manual or industrial occupations are the most vulnerable to globalization, but so are physicists and mathematicians!</p>
<p>Just to complete the picture, we also look at the least exposed occupations:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>scores <span class="sc">%&gt;%</span> </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(BK) <span class="sc">%&gt;%</span> </span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 7
  occupation           RTI_alm_isco_77     BK OFF1_ffl OFF2_ffl OFF3_ffl OFF_gms
  &lt;dbl+lbl&gt;                      &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;
1 83 [Drivers and mob…         -1.50   -0.999   0.399   -1.37     0.703   -0.628
2 51 [Personal and pr…         -0.598  -0.937  -0.910    0.312    0.240   -0.639
3 71 [Extraction and …         -0.185  -0.934   0.603   -1.23     0.0133  -0.593
4 52 [Models, salespe…          0.0534 -0.893   0.0565   0.913    1.34    -0.639
5 91 [Sales and servi…          0.0274 -0.808   0.729    0.0522   1.52    -0.375
6 22 [Life science an…         -1.00   -0.758  -1.92     0.544   -1.70    -0.639</code></pre>
</div>
</div>
<p>Here, it is again some manual workers (e.g., drivers and builders) that top the list (or, rather, are at the bottom). However, salespersons and medical professionals, who obviously cannot do their jobs from abroad, also have low exposure to globalization.</p>
</section>
<section id="adjusting-the-isco-scores" class="level3">
<h3 class="anchored" data-anchor-id="adjusting-the-isco-scores">Adjusting the ISCO scores</h3>
<p>As mentioned, the vulnerability score data are based on the ISCO-88 occupational classification, which is an older version of the ISCO-08 classifcation that is used to measure the occupation of <em>ESS</em> respondents. In addition, you may have noticed that the ISCO-scores in the <em>ESS</em> data have four numbers while those in the vulnerability data have two. The latter is because the vulnerability data use a simplified or less fine-grained version of the ISCO classification.</p>
<p>This means that to be able to merge the two datasets, we need to make sure that both use the same ISCO-classification so that we can match the different occupations, and that they are measured at the same level of detail.</p>
<p>Fortunately, there are methods to convert the scores back and forth between the different versions of the ISCO classification, and one of these is the <code>occupar</code> package (similar to the <code>DIGCLASS</code> package that is used in the the other post on <a href="https://cknotz.github.io/getstuffdone_blog/posts/measuringclass/" target="_blank">measuring class</a>). In case you do not already have it installed, you can do so by running the following in your <em>Console</em>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>remotes<span class="sc">::</span><span class="fu">install_github</span>(<span class="st">"DiogoFerrari/occupar"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Technically, we could either adjust the ISCO-08 scores in the <em>ESS</em> to match the ISCO-88 scores used in the other dataset, or the other way around, and the <code>occupar</code> package has functions to do both. The only important thing is that both datasets contain the same version of the ISCO classication.</p>
<p>We will use the <code>isco08to88()</code> function which, as the name suggests, converts ISCO-08 scores in the <em>ESS</em> to ISCO-88 scores, so that we can then match the <em>ESS</em> data and the vulnerability indicators along these scores and merge the two datasets. This function needs the numerical ISCO scores (not the titles of the occupations but the associated numbers).</p>
<p>This means that we need to extract the numerical scores from the ISCO-08 variable in the <em>ESS</em>. The following code does this and stores the converted scores into a new variable:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>ess7 <span class="sc">%&gt;%</span> </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">isco08_scores =</span> <span class="fu">as.numeric</span>(isco08)) <span class="ot">-&gt;</span> ess7</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We can take a quick look at the data to see if the conversion worked:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ess7)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 8
   idno cntry essround isco08                gndr    agea  trstplt isco08_scores
  &lt;dbl&gt; &lt;chr&gt;    &lt;dbl&gt; &lt;dbl+lbl&gt;             &lt;dbl+l&gt; &lt;dbl&gt; &lt;dbl+l&gt;         &lt;dbl&gt;
1     1 AT           7  7126 [Plumbers and … 1 [Mal… 51    3 [3]            7126
2     2 AT           7  8312 [Railway brake… 1 [Mal… 67    3 [3]            8312
3     3 AT           7 NA(a) [Not applicabl… 2 [Fem… 89    3 [3]              NA
4     4 AT           7  7223 [Metal working… 1 [Mal… 32    0 [No …          7223
5     5 AT           7  9321 [Hand packers]  2 [Fem… 56    0 [No …          9321
6     6 AT           7  9321 [Hand packers]  2 [Fem… 67    0 [No …          9321</code></pre>
</div>
</div>
<p>Indeed, the function worked as intended. For example, it correctly extracted the ISCO-08 score <code>7126</code> for the “plumber” in row #1 and saved it as <code>7126</code> in the new variable.</p>
<p>This means we can now convert the new scores to the ISCO-88 classification:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>ess7 <span class="sc">%&gt;%</span> </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">isco88 =</span> occupar<span class="sc">::</span><span class="fu">isco08to88</span>(isco08_scores)) <span class="ot">-&gt;</span> ess7</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>If we take another quick look at the dataset, you can see the new ISCO-88 scores in the last column; you may also notice that the scores are slightly different (for example, <code>9321</code> in the ISCO-08 classification is <code>9322</code> in the old one):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ess7)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 9
   idno cntry essround isco08         gndr    agea  trstplt isco08_scores isco88
  &lt;dbl&gt; &lt;chr&gt;    &lt;dbl&gt; &lt;dbl+lbl&gt;      &lt;dbl+l&gt; &lt;dbl&gt; &lt;dbl+l&gt;         &lt;dbl&gt;  &lt;dbl&gt;
1     1 AT           7  7126 [Plumbe… 1 [Mal… 51    3 [3]            7126   7136
2     2 AT           7  8312 [Railwa… 1 [Mal… 67    3 [3]            8312   8312
3     3 AT           7 NA(a) [Not ap… 2 [Fem… 89    3 [3]              NA     NA
4     4 AT           7  7223 [Metal … 1 [Mal… 32    0 [No …          7223   7223
5     5 AT           7  9321 [Hand p… 2 [Fem… 56    0 [No …          9321   9322
6     6 AT           7  9321 [Hand p… 2 [Fem… 67    0 [No …          9321   9322</code></pre>
</div>
</div>
<p>The almost last step in the data preparation is to “simplify” the new ISCO-88 scores in the <em>ESS</em> data to the same level of detail that the vulnerability data have. This is relatively easy, we simply “extract” the first two numbers of the four-number ISCO-scores.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> The following code does that:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>ess7 <span class="sc">%&gt;%</span> </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">isco88_2d =</span> <span class="fu">as.numeric</span>(<span class="fu">substr</span>(<span class="fu">as.character</span>(isco88), <span class="dv">1</span>,<span class="dv">2</span>))) <span class="ot">-&gt;</span> ess7</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>In human language, this code first converts the <code>isco88</code> variable to text (<code>as.character()</code>), then uses <code>substr()</code> to extract the first two items (“from 1 to 2”), and then converts the result back to numbers with <code>as.numeric()</code>.</p>
<p>If we take a look at the final result (with variables re-arranged so that we can see them next to each other), we can confirm that all worked as it should:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>ess7 <span class="sc">%&gt;%</span> </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">relocate</span>(idno,cntry,essround,isco08,isco88,isco88_2d) <span class="sc">%&gt;%</span> </span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 10
   idno cntry essround isco08             isco88 isco88_2d gndr    agea  trstplt
  &lt;dbl&gt; &lt;chr&gt;    &lt;dbl&gt; &lt;dbl+lbl&gt;           &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl+l&gt; &lt;dbl&gt; &lt;dbl+l&gt;
1     1 AT           7  7126 [Plumbers a…   7136        71 1 [Mal… 51    3 [3]  
2     2 AT           7  8312 [Railway br…   8312        83 1 [Mal… 67    3 [3]  
3     3 AT           7 NA(a) [Not applic…     NA        NA 2 [Fem… 89    3 [3]  
4     4 AT           7  7223 [Metal work…   7223        72 1 [Mal… 32    0 [No …
5     5 AT           7  9321 [Hand packe…   9322        93 2 [Fem… 56    0 [No …
6     6 AT           7  9321 [Hand packe…   9322        93 2 [Fem… 67    0 [No …
# ℹ 1 more variable: isco08_scores &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Finally, we quickly convert the ISCO-88 scores in the vulnerability dataset to a pure numerical score. We also give it the same name as the corresponding variable in the <em>ESS</em> dataset to make merging the two datasets more straightforward:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>scores <span class="sc">%&gt;%</span> </span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">isco88_2d =</span> <span class="fu">as.numeric</span>(occupation)) <span class="ot">-&gt;</span> scores</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="merging-the-datasets" class="level3">
<h3 class="anchored" data-anchor-id="merging-the-datasets">Merging the datasets</h3>
<p>Merging two datasets can seem a bit daunting to beginners, but it is actually not that difficult. The <code>dplyr</code> package has functions for so-called “mutating joins” (see <a href="https://dplyr.tidyverse.org/reference/mutate-joins.html" target="_blank">https://dplyr.tidyverse.org/reference/mutate-joins.html</a>), which in essence simply merge two datasets along one (or potentially more) “identifier” variable.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> Identifier variables are variables that uniquely identify a given observation in both datasets so that <code>R</code> knows exactly which row in dataset 1 corresponds to which row in dataset 2. As long as one has one (or more) variables that can directly match observations between datasets – which in our case is the two-number ISCO-88 score – one can use these functions to merge two datasets.</p>
<p>Usually, the correct function to use to merge datasets is <code>left_join()</code>. In our case, we want to join the <em>ESS</em> dataset with the vulnerability scores dataset along the two-digit ISCO-88 scores, so we specify this in our code:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>ess7 <span class="sc">%&gt;%</span> </span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(scores, <span class="at">by =</span> <span class="st">"isco88_2d"</span>) <span class="ot">-&gt;</span> ess7</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>And that is it.</p>
<p>If we take a look at the relevant variables in the final dataset, we can see the vulnerability scores matched to the <em>ESS</em> data:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>ess7 <span class="sc">%&gt;%</span> </span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(idno,isco08,isco88_2d,BK,RTI_alm_isco_77) <span class="sc">%&gt;%</span> </span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
   idno isco08                                  isco88_2d     BK RTI_alm_isco_77
  &lt;dbl&gt; &lt;dbl+lbl&gt;                                   &lt;dbl&gt;  &lt;dbl&gt;           &lt;dbl&gt;
1     1  7126 [Plumbers and pipe fitters]              71 -0.934          -0.185
2     2  8312 [Railway brake, signal and switc…        83 -0.999          -1.50 
3     3 NA(a) [Not applicable]                         NA NA              NA    
4     4  7223 [Metal working machine tool sett…        72 -0.451           0.457
5     5  9321 [Hand packers]                           93 -0.658           0.449
6     6  9321 [Hand packers]                           93 -0.658           0.449</code></pre>
</div>
</div>
<p>You see that respondent with ID number 1 (the plumber) has a <code>BK</code> offshorability score of -9.34 and also an automation-vulnerability (RTI) score of -0.185.</p>
<p>As a last step, we convert the final dataset to the traditional <code>R</code> format so that it is easier to work with later:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>ess7 <span class="ot">&lt;-</span> labelled<span class="sc">::</span><span class="fu">unlabelled</span>(ess7)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
</section>
<section id="vulnerability-to-globalization-gender-age-and-political-trust" class="level2">
<h2 class="anchored" data-anchor-id="vulnerability-to-globalization-gender-age-and-political-trust">Vulnerability to globalization, gender, age, and political trust</h2>
<p>With the merged data in hand, we can now do lots of different analyses. For example, we could use the vulnerabiility scores in a regression analysis to see if they are related to some other variable. Just to illustrate this, we will do a few quick visual analyses of the relationships between the offshoreability scores and gender, age, and political trust.</p>
<p>For example, let’s see if men or women are on average more exposed to globalization:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>ess7 <span class="sc">%&gt;%</span> </span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(gndr) <span class="sc">%&gt;%</span> </span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">avg_BK =</span> <span class="fu">mean</span>(BK, <span class="at">na.rm =</span> T)) <span class="sc">%&gt;%</span> </span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>() <span class="sc">%&gt;%</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> gndr, <span class="at">y =</span> avg_BK)) <span class="sc">+</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_col</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="index_files/figure-html/unnamed-chunk-22-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1"><img src="index_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
</div>
<p>There is only a tiny difference: Women are very slightly less exposed to globalization than men.</p>
<p>Next, we can see if there is a relation to age. To do that, we can calculate the average age in a given occupation and relate that average age to the vulnerability score in a scatterplot. Note that we use <code>geom_text()</code> to add the occupation titles to the graph:</p>
<div class="cell preview-image">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>ess7 <span class="sc">%&gt;%</span> </span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(occupation) <span class="sc">%&gt;%</span> </span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">avg_age =</span> <span class="fu">mean</span>(agea, <span class="at">na.rm =</span> T),</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">avg_BK =</span> <span class="fu">mean</span>(BK, <span class="at">na.rm =</span> T)) <span class="sc">%&gt;%</span> </span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> avg_age, <span class="at">y =</span> avg_BK)) <span class="sc">+</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> occupation), <span class="at">vjust =</span> <span class="dv">1</span>, </span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>              <span class="at">color =</span> <span class="st">"grey"</span>,</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>              <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"grey"</span>, </span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>                <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">se =</span> F) <span class="sc">+</span></span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Average age in occupational group"</span>,</span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>         <span class="at">y =</span> <span class="st">"Average offshoreability"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="index_files/figure-html/unnamed-chunk-23-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2"><img src="index_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
</div>
<p>There does seem to be a positive relationship: Occupations where workers are older are also more exposed to globalization.</p>
<p>Finally, let’s see if exposure to globalization has political effects by testing if there is a relationship to trust in politicians. We can do this in more fancy way with a hexbin plot (and relatively large bin sizes):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>ess7 <span class="sc">%&gt;%</span> </span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(trstplt,BK) <span class="sc">%&gt;%</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">trstplt_num =</span> <span class="fu">as.numeric</span>(trstplt)<span class="sc">-</span><span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">y =</span> trstplt_num, <span class="at">x =</span> BK)) <span class="sc">+</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_hex</span>(<span class="at">binwidth =</span> <span class="fu">c</span>(.<span class="dv">75</span>,<span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="index_files/figure-html/unnamed-chunk-24-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3"><img src="index_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
</div>
<p>At least based on this (admittedly) very quick and superficial look at the data, there does not seem to be a clear relationship.</p>
</section>
<section id="next-steps" class="level2">
<h2 class="anchored" data-anchor-id="next-steps">Next steps</h2>
<p>Even if there is not link to political trust, maybe you can think of other variables that are measured in the <em>ESS</em> that globalization vulnerability could have an effect on? And maybe you can even think of macro-level variables that could make these effects stronger or weaker (and then use <a href="https://cknotz.github.io/getstuffdone_blog/posts/compa_survey/" target="_blank">the other post</a> to compare the effects of globalization vulnerability between two or more selected countries that differ in relevant ways on these variables)?</p>
<p>Finally, you can also merge the vulnerability scores to other survey datasets such as the <em>ISSP</em> or the <em>Eurobarometer</em> so long as the survey dataset contains ISCO occupation scores.</p>



</section>


<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-Agnolinetal2025" class="csl-entry" role="listitem">
Agnolin, Paolo, Italo Colantone, and Piero Stanig. 2025. <span>“In Search of the Causes of the Globalization Backlash: Methodological Considerations on Post-Treatment Bias.”</span> <em>Comparative Political Studies</em> 58 (8): 1603–35.
</div>
<div id="ref-Autoretal2019" class="csl-entry" role="listitem">
Autor, David H., David Dorn, and Gordon Hanson. 2019. <span>“When Work Disappears: <span>Manufacturing</span> Decline and the Falling Marriage Market Value of Young Men.”</span> <em>American Economic Review</em> 1 (2): 161–78.
</div>
<div id="ref-Autoretal2013" class="csl-entry" role="listitem">
Autor, David H., David Dorn, and Gordon H Hanson. 2013. <span>“<span class="nocase">The China syndrome: Local labor market effects of import competition in the United States</span>.”</span> <em>American Economic Review</em> 103 (6): 2121–68.
</div>
<div id="ref-Autoretal2020" class="csl-entry" role="listitem">
Autor, David H., David Dorn, Gordon Hanson, and Kaveh Majlesi. 2020. <span>“Importing Political Polarization? <span>The</span> Electoral Consequences of Rising Trade Exposure.”</span> <em>American Economic Review</em> 110 (10): 3139–83.
</div>
<div id="ref-Autoretal2003" class="csl-entry" role="listitem">
Autor, David H., Frank Levy, and Richard J. Murnane. 2003. <span>“The Skill Content of Recent Technological Change: An Empirical Exploration.”</span> <em>Quarterly Journal of Economics</em> 118 (4): 1279–1333.
</div>
<div id="ref-Blinder2013" class="csl-entry" role="listitem">
Blinder, Alan S, and Alan B Krueger. 2013. <span>“Alternative Measures of Offshorability: A Survey Approach.”</span> <em>Journal of Labor Economics</em> 31 (S1): S97–128.
</div>
<div id="ref-Colantone2018a" class="csl-entry" role="listitem">
Colantone, Italo, and Piero Stanig. 2018a. <span>“Global Competition and <span>Brexit</span>.”</span> <em>American Political Science Review</em> 112 (2): 201–18.
</div>
<div id="ref-Colantone2018" class="csl-entry" role="listitem">
———. 2018b. <span>“The Trade Origins of Economic Nationalism: Import Competition and Voting Behavior in <span>Western Europe</span>.”</span> <em>American Journal of Political Science</em> 62 (4): 936–53.
</div>
<div id="ref-Colantone2019" class="csl-entry" role="listitem">
———. 2019. <span>“The Surge of Economic Nationalism in <span>Western Europe</span>.”</span> <em>Journal of Economic Perspectives</em> 33 (4): 128–51.
</div>
<div id="ref-Firpoetal2011" class="csl-entry" role="listitem">
Firpo, Sergio, Nicole M Fortin, and Thomas Lemieux. 2011. <span>“Occupational Tasks and Changes in the Wage Structure.”</span> <em>IZA Discussion Paper</em> 5542.
</div>
<div id="ref-Goosetal2014" class="csl-entry" role="listitem">
Goos, Maarten, Alan Manning, and Anna Salomons. 2014. <span>“Explaining Job Polarization: Routine-Biased Technological Change and Offshoring.”</span> <em>American Economic Review</em> 104 (8): 2509–26.
</div>
<div id="ref-Heckscher1919" class="csl-entry" role="listitem">
Heckscher, Eli F. 1919. <span>“Utrikeshandelns Verkan p<span>å</span> Inkomstf<span>ö</span>rdelningen. N<span>å</span>gra Teoretiska Grundlinjer.”</span> <em>Ekonomisk Tidskrift</em> 21: 1–31.
</div>
<div id="ref-Ohlin1933" class="csl-entry" role="listitem">
Ohlin, Bertil. 1933. <em>Interregional and International Trade</em>. Cambridge, MA: Harvard University Press.
</div>
<div id="ref-Thewissen2019" class="csl-entry" role="listitem">
Thewissen, Stefan, and David Rueda. 2019. <span>“Automation and the Welfare State: Technological Change as a Determinant of Redistribution Preferences.”</span> <em>Comparative Political Studies</em> 52 (2): 171–208.
</div>
<div id="ref-Urdinez2020" class="csl-entry" role="listitem">
Urdinez, Francisco, and Andres Cruz. 2020. <em>R for Political Data Science: A Practical Guide</em>. Boca Raton; others: CRC Press.
</div>
<div id="ref-Walter2010" class="csl-entry" role="listitem">
Walter, Stefanie. 2010. <span>“Globalization and the Welfare State: Testing the Microfoundations of the Compensation Hypothesis.”</span> <em>International Studies Quarterly</em> 54 (2): 403–26.
</div>
</div></section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>See <a href="https://ilostat.ilo.org/methods/concepts-and-definitions/classification-occupation/" target="_blank">https://ilostat.ilo.org/methods/concepts-and-definitions/classification-occupation/</a> for details on the ISCO classification.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>This works because the numbers reflect the hierarchical structure of the ISCO classification. If we cut off the last two numbers, we get to a higher level of aggregation. See <a href="https://ilostat.ilo.org/methods/concepts-and-definitions/classification-occupation/#elementor-toc__heading-anchor-2" target="_blank">https://ilostat.ilo.org/methods/concepts-and-definitions/classification-occupation/#elementor-toc__heading-anchor-2</a> for details.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>If you want a more detailed explanation of how to merge two datasets, you can read <a href="https://cknotz.github.io/getstuffdone_blog/posts/merging/">this post</a>, which also contains links to other online resources, or Chapter 11.2 in Urdinez &amp; Cruz <span class="citation" data-cites="Urdinez2020">(<a href="#ref-Urdinez2020" role="doc-biblioref">2020</a>)</span>.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section><section class="quarto-appendix-contents" id="quarto-citation"><h2 class="anchored quarto-appendix-heading">Citation</h2><div><div class="quarto-appendix-secondary-label">BibTeX citation:</div><pre class="sourceCode code-with-copy quarto-appendix-bibtex"><code class="sourceCode bibtex">@online{knotz2025,
  author = {Knotz, Carlo},
  title = {How Vulnerable Are Workers to Globalization (and What Effects
    Does This Have)?},
  date = {2025-03-10},
  url = {https://cknotz.github.io/getstuffdone_blog/posts/globalization/},
  langid = {en}
}
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre><div class="quarto-appendix-secondary-label">For attribution, please cite this work as:</div><div id="ref-knotz2025" class="csl-entry quarto-appendix-citeas" role="listitem">
Knotz, Carlo. 2025. <span>“How Vulnerable Are Workers to Globalization
(and What Effects Does This Have)?”</span> March 10, 2025. <a href="https://cknotz.github.io/getstuffdone_blog/posts/globalization/">https://cknotz.github.io/getstuffdone_blog/posts/globalization/</a>.
</div></div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
            // default icon
            link.classList.add("external");
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>